{"ast":null,"code":"import { getCurrentHub } from '@sentry/core';\nimport { Severity } from '@sentry/types';\nimport { logger } from '@sentry/utils';\nimport { logAndExitProcess } from '../handlers';\n/** Global Promise Rejection handler */\nvar OnUncaughtException = /** @class */function () {\n  /**\n   * @inheritDoc\n   */\n  function OnUncaughtException(_options) {\n    if (_options === void 0) {\n      _options = {};\n    }\n    this._options = _options;\n    /**\n     * @inheritDoc\n     */\n    this.name = OnUncaughtException.id;\n    /**\n     * @inheritDoc\n     */\n    this.handler = this._makeErrorHandler();\n  }\n  /**\n   * @inheritDoc\n   */\n  OnUncaughtException.prototype.setupOnce = function () {\n    global.process.on('uncaughtException', this.handler.bind(this));\n  };\n  /**\n   * @hidden\n   */\n  OnUncaughtException.prototype._makeErrorHandler = function () {\n    var _this = this;\n    var timeout = 2000;\n    var caughtFirstError = false;\n    var caughtSecondError = false;\n    var calledFatalError = false;\n    var firstError;\n    return function (error) {\n      var onFatalError = logAndExitProcess;\n      var client = getCurrentHub().getClient();\n      if (_this._options.onFatalError) {\n        // eslint-disable-next-line @typescript-eslint/unbound-method\n        onFatalError = _this._options.onFatalError;\n      } else if (client && client.getOptions().onFatalError) {\n        // eslint-disable-next-line @typescript-eslint/unbound-method\n        onFatalError = client.getOptions().onFatalError;\n      }\n      if (!caughtFirstError) {\n        var hub_1 = getCurrentHub();\n        // this is the first uncaught error and the ultimate reason for shutting down\n        // we want to do absolutely everything possible to ensure it gets captured\n        // also we want to make sure we don't go recursion crazy if more errors happen after this one\n        firstError = error;\n        caughtFirstError = true;\n        if (hub_1.getIntegration(OnUncaughtException)) {\n          hub_1.withScope(function (scope) {\n            scope.setLevel(Severity.Fatal);\n            hub_1.captureException(error, {\n              originalException: error\n            });\n            if (!calledFatalError) {\n              calledFatalError = true;\n              onFatalError(error);\n            }\n          });\n        } else {\n          if (!calledFatalError) {\n            calledFatalError = true;\n            onFatalError(error);\n          }\n        }\n      } else if (calledFatalError) {\n        // we hit an error *after* calling onFatalError - pretty boned at this point, just shut it down\n        logger.warn('uncaught exception after calling fatal error shutdown callback - this is bad! forcing shutdown');\n        logAndExitProcess(error);\n      } else if (!caughtSecondError) {\n        // two cases for how we can hit this branch:\n        //   - capturing of first error blew up and we just caught the exception from that\n        //     - quit trying to capture, proceed with shutdown\n        //   - a second independent error happened while waiting for first error to capture\n        //     - want to avoid causing premature shutdown before first error capture finishes\n        // it's hard to immediately tell case 1 from case 2 without doing some fancy/questionable domain stuff\n        // so let's instead just delay a bit before we proceed with our action here\n        // in case 1, we just wait a bit unnecessarily but ultimately do the same thing\n        // in case 2, the delay hopefully made us wait long enough for the capture to finish\n        // two potential nonideal outcomes:\n        //   nonideal case 1: capturing fails fast, we sit around for a few seconds unnecessarily before proceeding correctly by calling onFatalError\n        //   nonideal case 2: case 2 happens, 1st error is captured but slowly, timeout completes before capture and we treat second error as the sendErr of (nonexistent) failure from trying to capture first error\n        // note that after hitting this branch, we might catch more errors where (caughtSecondError && !calledFatalError)\n        //   we ignore them - they don't matter to us, we're just waiting for the second error timeout to finish\n        caughtSecondError = true;\n        setTimeout(function () {\n          if (!calledFatalError) {\n            // it was probably case 1, let's treat err as the sendErr and call onFatalError\n            calledFatalError = true;\n            onFatalError(firstError, error);\n          } else {\n            // it was probably case 2, our first error finished capturing while we waited, cool, do nothing\n          }\n        }, timeout); // capturing could take at least sendTimeout to fail, plus an arbitrary second for how long it takes to collect surrounding source etc\n      }\n    };\n  };\n  /**\n   * @inheritDoc\n   */\n  OnUncaughtException.id = 'OnUncaughtException';\n  return OnUncaughtException;\n}();\nexport { OnUncaughtException };","map":{"version":3,"names":["getCurrentHub","Severity","logger","logAndExitProcess","OnUncaughtException","_options","name","id","handler","_makeErrorHandler","prototype","setupOnce","global","process","on","bind","_this","timeout","caughtFirstError","caughtSecondError","calledFatalError","firstError","error","onFatalError","client","getClient","getOptions","hub_1","getIntegration","withScope","scope","setLevel","Fatal","captureException","originalException","warn","setTimeout"],"sources":["C:\\Users\\rares\\Desktop\\Blockchain\\Proiect\\node_modules\\@sentry\\node\\src\\integrations\\onuncaughtexception.ts"],"sourcesContent":["import { getCurrentHub, Scope } from '@sentry/core';\nimport { Integration, Severity } from '@sentry/types';\nimport { logger } from '@sentry/utils';\n\nimport { NodeClient } from '../client';\nimport { logAndExitProcess } from '../handlers';\n\n/** Global Promise Rejection handler */\nexport class OnUncaughtException implements Integration {\n  /**\n   * @inheritDoc\n   */\n  public static id: string = 'OnUncaughtException';\n\n  /**\n   * @inheritDoc\n   */\n  public name: string = OnUncaughtException.id;\n\n  /**\n   * @inheritDoc\n   */\n  public readonly handler: (error: Error) => void = this._makeErrorHandler();\n\n  /**\n   * @inheritDoc\n   */\n  public constructor(\n    private readonly _options: {\n      /**\n       * Default onFatalError handler\n       * @param firstError Error that has been thrown\n       * @param secondError If this was called multiple times this will be set\n       */\n      onFatalError?(firstError: Error, secondError?: Error): void;\n    } = {},\n  ) {}\n  /**\n   * @inheritDoc\n   */\n  public setupOnce(): void {\n    global.process.on('uncaughtException', this.handler.bind(this));\n  }\n\n  /**\n   * @hidden\n   */\n  private _makeErrorHandler(): (error: Error) => void {\n    const timeout = 2000;\n    let caughtFirstError: boolean = false;\n    let caughtSecondError: boolean = false;\n    let calledFatalError: boolean = false;\n    let firstError: Error;\n\n    return (error: Error): void => {\n      type onFatalErrorHandlerType = (firstError: Error, secondError?: Error) => void;\n\n      let onFatalError: onFatalErrorHandlerType = logAndExitProcess;\n      const client = getCurrentHub().getClient<NodeClient>();\n\n      if (this._options.onFatalError) {\n        // eslint-disable-next-line @typescript-eslint/unbound-method\n        onFatalError = this._options.onFatalError;\n      } else if (client && client.getOptions().onFatalError) {\n        // eslint-disable-next-line @typescript-eslint/unbound-method\n        onFatalError = client.getOptions().onFatalError as onFatalErrorHandlerType;\n      }\n\n      if (!caughtFirstError) {\n        const hub = getCurrentHub();\n\n        // this is the first uncaught error and the ultimate reason for shutting down\n        // we want to do absolutely everything possible to ensure it gets captured\n        // also we want to make sure we don't go recursion crazy if more errors happen after this one\n        firstError = error;\n        caughtFirstError = true;\n\n        if (hub.getIntegration(OnUncaughtException)) {\n          hub.withScope((scope: Scope) => {\n            scope.setLevel(Severity.Fatal);\n            hub.captureException(error, { originalException: error });\n            if (!calledFatalError) {\n              calledFatalError = true;\n              onFatalError(error);\n            }\n          });\n        } else {\n          if (!calledFatalError) {\n            calledFatalError = true;\n            onFatalError(error);\n          }\n        }\n      } else if (calledFatalError) {\n        // we hit an error *after* calling onFatalError - pretty boned at this point, just shut it down\n        logger.warn('uncaught exception after calling fatal error shutdown callback - this is bad! forcing shutdown');\n        logAndExitProcess(error);\n      } else if (!caughtSecondError) {\n        // two cases for how we can hit this branch:\n        //   - capturing of first error blew up and we just caught the exception from that\n        //     - quit trying to capture, proceed with shutdown\n        //   - a second independent error happened while waiting for first error to capture\n        //     - want to avoid causing premature shutdown before first error capture finishes\n        // it's hard to immediately tell case 1 from case 2 without doing some fancy/questionable domain stuff\n        // so let's instead just delay a bit before we proceed with our action here\n        // in case 1, we just wait a bit unnecessarily but ultimately do the same thing\n        // in case 2, the delay hopefully made us wait long enough for the capture to finish\n        // two potential nonideal outcomes:\n        //   nonideal case 1: capturing fails fast, we sit around for a few seconds unnecessarily before proceeding correctly by calling onFatalError\n        //   nonideal case 2: case 2 happens, 1st error is captured but slowly, timeout completes before capture and we treat second error as the sendErr of (nonexistent) failure from trying to capture first error\n        // note that after hitting this branch, we might catch more errors where (caughtSecondError && !calledFatalError)\n        //   we ignore them - they don't matter to us, we're just waiting for the second error timeout to finish\n        caughtSecondError = true;\n        setTimeout(() => {\n          if (!calledFatalError) {\n            // it was probably case 1, let's treat err as the sendErr and call onFatalError\n            calledFatalError = true;\n            onFatalError(firstError, error);\n          } else {\n            // it was probably case 2, our first error finished capturing while we waited, cool, do nothing\n          }\n        }, timeout); // capturing could take at least sendTimeout to fail, plus an arbitrary second for how long it takes to collect surrounding source etc\n      }\n    };\n  }\n}\n"],"mappings":"AAAA,SAASA,aAAa,QAAe,cAAc;AACnD,SAAsBC,QAAQ,QAAQ,eAAe;AACrD,SAASC,MAAM,QAAQ,eAAe;AAGtC,SAASC,iBAAiB,QAAQ,aAAa;AAE/C;AACA,IAAAC,mBAAA;EAgBE;;;EAGA,SAAAA,oBACmBC,QAOX;IAPW,IAAAA,QAAA;MAAAA,QAAA,KAOX;IAAA;IAPW,KAAAA,QAAQ,GAARA,QAAQ;IAd3B;;;IAGO,KAAAC,IAAI,GAAWF,mBAAmB,CAACG,EAAE;IAE5C;;;IAGgB,KAAAC,OAAO,GAA2B,IAAI,CAACC,iBAAiB,EAAE;EAcvE;EACH;;;EAGOL,mBAAA,CAAAM,SAAA,CAAAC,SAAS,GAAhB;IACEC,MAAM,CAACC,OAAO,CAACC,EAAE,CAAC,mBAAmB,EAAE,IAAI,CAACN,OAAO,CAACO,IAAI,CAAC,IAAI,CAAC,CAAC;EACjE,CAAC;EAED;;;EAGQX,mBAAA,CAAAM,SAAA,CAAAD,iBAAiB,GAAzB;IAAA,IAAAO,KAAA;IACE,IAAMC,OAAO,GAAG,IAAI;IACpB,IAAIC,gBAAgB,GAAY,KAAK;IACrC,IAAIC,iBAAiB,GAAY,KAAK;IACtC,IAAIC,gBAAgB,GAAY,KAAK;IACrC,IAAIC,UAAiB;IAErB,OAAO,UAACC,KAAY;MAGlB,IAAIC,YAAY,GAA4BpB,iBAAiB;MAC7D,IAAMqB,MAAM,GAAGxB,aAAa,EAAE,CAACyB,SAAS,EAAc;MAEtD,IAAIT,KAAI,CAACX,QAAQ,CAACkB,YAAY,EAAE;QAC9B;QACAA,YAAY,GAAGP,KAAI,CAACX,QAAQ,CAACkB,YAAY;OAC1C,MAAM,IAAIC,MAAM,IAAIA,MAAM,CAACE,UAAU,EAAE,CAACH,YAAY,EAAE;QACrD;QACAA,YAAY,GAAGC,MAAM,CAACE,UAAU,EAAE,CAACH,YAAuC;;MAG5E,IAAI,CAACL,gBAAgB,EAAE;QACrB,IAAMS,KAAG,GAAG3B,aAAa,EAAE;QAE3B;QACA;QACA;QACAqB,UAAU,GAAGC,KAAK;QAClBJ,gBAAgB,GAAG,IAAI;QAEvB,IAAIS,KAAG,CAACC,cAAc,CAACxB,mBAAmB,CAAC,EAAE;UAC3CuB,KAAG,CAACE,SAAS,CAAC,UAACC,KAAY;YACzBA,KAAK,CAACC,QAAQ,CAAC9B,QAAQ,CAAC+B,KAAK,CAAC;YAC9BL,KAAG,CAACM,gBAAgB,CAACX,KAAK,EAAE;cAAEY,iBAAiB,EAAEZ;YAAK,CAAE,CAAC;YACzD,IAAI,CAACF,gBAAgB,EAAE;cACrBA,gBAAgB,GAAG,IAAI;cACvBG,YAAY,CAACD,KAAK,CAAC;;UAEvB,CAAC,CAAC;SACH,MAAM;UACL,IAAI,CAACF,gBAAgB,EAAE;YACrBA,gBAAgB,GAAG,IAAI;YACvBG,YAAY,CAACD,KAAK,CAAC;;;OAGxB,MAAM,IAAIF,gBAAgB,EAAE;QAC3B;QACAlB,MAAM,CAACiC,IAAI,CAAC,gGAAgG,CAAC;QAC7GhC,iBAAiB,CAACmB,KAAK,CAAC;OACzB,MAAM,IAAI,CAACH,iBAAiB,EAAE;QAC7B;QACA;QACA;QACA;QACA;QACA;QACA;QACA;QACA;QACA;QACA;QACA;QACA;QACA;QACAA,iBAAiB,GAAG,IAAI;QACxBiB,UAAU,CAAC;UACT,IAAI,CAAChB,gBAAgB,EAAE;YACrB;YACAA,gBAAgB,GAAG,IAAI;YACvBG,YAAY,CAACF,UAAU,EAAEC,KAAK,CAAC;WAChC,MAAM;YACL;UAAA;QAEJ,CAAC,EAAEL,OAAO,CAAC,CAAC,CAAC;;IAEjB,CAAC;EACH,CAAC;EAlHD;;;EAGcb,mBAAA,CAAAG,EAAE,GAAW,qBAAqB;EAgHlD,OAAAH,mBAAC;CAAA,CApHD;SAAaA,mBAAmB","ignoreList":[]},"metadata":{},"sourceType":"module","externalDependencies":[]}